config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  # create routes for #new and #create actions
  # [only:] prevents Rails creating unnecessary routes

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :labels, only: [:show]

  get 'about' => 'welcome#about'

  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        member do
          post :create_post
          # post :create

        end
      end
      resources :posts, only: [:index, :show, :update, :destroy]
      resources :comments, only: [:index, :show]
    end
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>Let's talk #about text, < b>< /b>.</h1>
<br><br><br>

<b>
<button class="social-btn"><%= link_to "Follow me", "https://twitter.com/slyarboro" %></button>
</b>
<br><br>
<p>SLY</p>

app/views/welcome/contact.html.erb
<html>
  <body>
    <center>
      <p>
      Bloc 'em out RDoc, <i>-l</i>.<p>
      <b>Bloc 'em out</b>, <i>--l</i>.<p>
        <img src="https://media.giphy.com/media/xT5LMzWXhhaw3aOdFK/giphy.gif" style="max-width:100%"/>
      <p>

    </center>
  </body>
</html>

app/views/welcome/faq.html.erb
There's a time you've got to go and show you're growing; now you know about the FAQs of life.

  Q: The FAQs of what?

  A: The FAQs of life.

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Bloccit</h1>
   <p>Bloccit is a resource for sharing appropriate links with your friends!</p>
   <p>
     <%= link_to "Sign In", new_session_path %> or
     <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
   </p>
 </div>


 <div class="row">
   <div class="col-md-4">
     <h3>Determine</h3>
     <p>Check-ch-check-check-check git checkout .<br /> What-wha-what resources are in route?<br />
     When-wh-when unsure, comment code out.
   </p>
   </div>
   <div class="col-md-4">
     <h3>Confirm</h3>
     <p>I'm testing data migrations;
       <br />
        Confirming with validations.<br /> <i>(Good good good rails g migrations.)</i> </p>
   </div>
      <div class="col-md-4">
        <h3>Continue</h3>
        <p>Don't stop. Git it, git it<br />
          Start new repo: <i>git init</i><br />
        Commit, push, merge; don't  Ctrl+C  it</p>
      </div>
 </div>